In [1]:
import numpy as np

# Generate step data for 4 weeks (7 days per week)
# Each value is a random number between 3000 and 10000
step = np.random.randint(3000, 10000, size=(4, 7))

# Print the full step matrix (4 weeks x 7 days)
print("Step Data (Weeks x Days):\n", step)

# Calculate and print total steps taken in 4 weeks
print("Total steps:", np.sum(step))

# Calculate and print average steps per day
print("Average steps:", np.mean(step))

# Print the highest number of steps taken in a day
print("Max step:", np.max(step))

# Print the lowest number of steps taken in a day
print("Min step:", np.min(step))

# Identify lazy days (less than 5000 steps)
lazy_days = step < 5000

# Replace lazy days with 0
step[lazy_days] = 0

# Print cleaned data after replacing lazy days
print("\nCleaned Step Data (Lazy Days = 0):\n", step)

# Count how many lazy days occurred in total
number_of_lazy_days = np.sum(step == 0)
print("Number of lazy days:", number_of_lazy_days)


Step Data (Weeks x Days):
 [[7819 7938 3095 6168 9499 9181 7140]
 [6836 8346 3336 4136 5768 8777 9625]
 [8890 6137 6312 6786 5269 3388 5158]
 [9278 3800 7857 5148 4286 8267 6714]]
Total steps: 184954
Average steps: 6605.5
Max step: 9625
Min step: 3095

Cleaned Step Data (Lazy Days = 0):
 [[7819 7938    0 6168 9499 9181 7140]
 [6836 8346    0    0 5768 8777 9625]
 [8890 6137 6312 6786 5269    0 5158]
 [9278    0 7857 5148    0 8267 6714]]
Number of lazy days: 6
